<?xml version="1.0" ?>
<robot name="mrobot_chassis" xmlns:xacro="http://www.ros.org/wiki/xacro">

	<xacro:property name="M_PI" value="3.14159" />
	<xacro:property name="base_radius" value="0.13" />
	<xacro:property name="base_length" value="0.005" />
	<xacro:property name="wheel_radius" value="0.033" />
	<xacro:property name="wheel_length" value="0.017" />
	<xacro:property name="motor_radius" value="0.02" />
	<xacro:property name="motor_length" value="0.08" />
	<xacro:property name="wheel_joint_y" value="0.0485" />
	<xacro:property name="motor_x" value="-0.055" />
	<xacro:property name="motor_y" value="0.075" />
	<xacro:property name="plate_height" value="0.07" />
	<xacro:property name="standoff_x" value="0.12" />
	<xacro:property name="standoff_y" value="0.10" />
	<xacro:property name="castor_x" value="0.1135" />
	<xacro:property name="castor_z" value="-0.0165" />
	<xacro:property name="castor_radius" value="0.0165" />

	<material name="yellow">
		<color rgba="1 0.4 0 1" />
	</material>
	<material name="black">
		<color rgba="0 0 0 0.95" />
	</material>
	<material name="gray">
		<color rgba="0.75 0.75 0.75 1" />
	</material>


	
	<xacro:macro name="wheel" params="prefix reflect">
		<joint name="${prefix}_wheel_joint" type="continuous">
			<origin xyz="0 ${reflect*wheel_joint_y} 0" rpy="0 0 0" />
			<parent link="${prefix}_motor" />
			<child link="${prefix}_wheel_link" />
			<axis xyz="0 1 0" />
		</joint>
	
	
		<link name="${prefix}_wheel_link">
			<visual>
				<origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
				<geometry>
					<cylinder length="${wheel_length}" radius="${wheel_radius}" />
				</geometry>
				<material name="gray" />
			</visual>
		</link>
	</xacro:macro>

	<xacro:macro name="motor" params="prefix reflect">
		<joint name="base_${prefix}_motor_joint" type="fixed">
			<origin xyz="${motor_x} ${reflect*motor_y} 0" rpy="0 0 0" />
			<parent link="base_link" />
			<child link="${prefix}_motor" />
		</joint>
	
		<link name="${prefix}_motor">
			<visual>
				<origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
				<geometry>
					<cylinder length="${motor_length}" radius="${motor_radius}" />
				</geometry>
				<material name="gray" />
			</visual>
		</link>
	</xacro:macro>

	<xacro:macro name="castor" params="prefix reflect">
		<joint name="${prefix}_castor_joint" type="fixed">
			<origin xyz="${reflect*castor_x} 0 ${castor_z}" rpy="0 0 0" />
			<parent link="base_link" />
			<child link="${prefix}_castor_link" />
			<axis xyz="0 1 0" />
		</joint>
	
		<link name="${prefix}_castor_link">
			<visual>
				<origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
				<geometry>
					<sphere radius="${castor_radius}" />
				</geometry>
				<material name="black" />
			</visual>
		</link>
	</xacro:macro>

	<xacro:macro name="mbot_base">
		<link name="base_footprint">
			<visual>
				<origin xyz="0 0 0" rpy="0 0 0" />
				<geometry>
					<box size="0.001 0.001 0.001" />
				</geometry>
			</visual>
		</link>
		
		<joint name="base_footprint_joint" type="fixed">
			<origin xyz="0 0 ${base_length/2+base_radius*2}" rpy="0 0 0" />
			<parent link="base_link" />
			<child link="base_footprint" />
		</joint>
		
		<link name="base_link">
			<inertial>
				<mass value="2" />
				<origin xyz="0 0 0.0" />
				<inertia ixx="0.01" ixy="0.0" ixz="0.0"
					 iyy="0.01" iyz="0.0" izz="0.5" />
			</inertial>
			<visual>
				<origin xyz="0 0 0" rpy="0 0 0" />
				<geometry>
					<cylinder length="${base_length}" radius="${base_radius}" />
				</geometry>
				<material name="yellow" />
			</visual>
			
			<collision>
				<origin xyz="0 0 0" rpy="0 0 0" />
				<geometry>
					<cylinder length="${base_length}" radius="${base_radius}" />
				</geometry>
			</collision >
		</link>
		<motor prefix="left" reflect="-1" />
		<motor prefix="right" reflect="1" />	
		<wheel prefix="left" reflect="-1" />
		<wheel prefix="right" reflect="1" />
		<castor prefix="front" reflect="1" />
		<castor prefix="notfront" reflect="-1" />	
	</xacro:macro>
</robot>
